config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items, only: [:index, :show]
  resources :users, only: [:index]
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_twitter_card_info()
    twitter_card = {}
    twitter_card[:url] = 'https://linch.link'
    if @article.present?
      twitter_card[:title] = "#{@article.title.gsub(" ", "")}"
      twitter_card[:description] = "#{@article.title.gsub(" ", "")}"
    else
      twitter_card[:title] = 'Linch（リンク） '
      twitter_card[:description] = '助け合って検索しよう！'
    end
    twitter_card[:image] = 'https://i.gyazo.com/c58031232aa0cbe49d4776262201bc4a.png'
    twitter_card[:card] = 'summary'
    twitter_card
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="items-index">
  <% 3.times do %>
  <div class="item-group">
    <div class="title">よく乾杯されているお酒</div>
    <% 2.times do %>
    <div class="each-row">
      <% 2.times do %>
      <%= link_to item_path(1) do %>
      <div class="item">
        <div class="img">
          <%= image_tag("https://images-fe.ssl-images-amazon.com/images/I/3194SNNR5XL._SY445_QL70_.jpg") %>
        </div>
        <div class="item-name">
          カルサーダ・クイネア クイネア・レセルバ 750ml
        </div>
      </div>
      <% end %>
      <%= link_to item_path(1) do %>
      <div class="item">
        <div class="img">
          <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/312xQCNFHcL.jpg") %>
        </div>
        <div class="item-name">
          カルサーダ・クイネア クイネア・レセルバ 750ml
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="items-show">
  <div class="top">
    <div class="item-overview">
      <div>
        <div class="img">
          <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/312xQCNFHcL.jpg") %>
        </div>
        <div class="item-name">カルサーダ・クイネア クイネア・レセルバ 750ml</div>
        <div class="buttons">
          <%= link_to "みんなと乾杯する", items_path, class: "oblong-button main-color" %>
          <%= link_to "amazonで見る", "https://www.amazon.co.jp/%E6%BE%A4%E4%B9%83%E4%BA%95-%E7%B4%94%E7%B1%B3%E5%90%9F%E9%86%B8-%E8%92%BC%E5%A4%A9%EF%BC%88%E3%81%9D%E3%81%86%E3%81%A6%E3%82%93%EF%BC%89-1800%EF%BD%8D%EF%BD%8C%C3%971%E6%9C%AC/dp/B005PBIEAW/ref=lp_71611051_1_3_sspa?s=alcohol&ie=UTF8&qid=1552457511&sr=1-3-spons&psc=1", class: "oblong-button amazon-color", :target => "_blank" %>
          <div class="eval">
            <%= link_to image_tag("favorite_red_border.png"), items_path, class: "circle-button main-color" %>
            <%= link_to image_tag("like_red_border.png"), items_path, class: "circle-button" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom">
    <div class="content">
      <div class="all-reviews">
        <div class="title">みんなのレビュー</div>
        <% 3.times do %>
        <div class="review">
          <div class="user-info">
            <div class="img">
              <%= image_tag("https://i.gyazo.com/c022ae94fdfe4688247e7b2fdd5f283a.jpg") %>
            </div>
            <div class="name">
              @takoyaki0316
            </div>
          </div>
          <div class="body">
            hoge hoge hoge hoge hoge
          </div>
        </div>
        <% end %>
      </div>
      <div class="related-items">
        <div class="title">オススメのお酒</div>
        <% 3.times do %>
        <div class="item">
          <div class="img"><%= image_tag("https://images-fe.ssl-images-amazon.com/images/I/3194SNNR5XL._SY445_QL70_.jpg") %></div>
          <div class="name">hoge hoge hoge</div>
        </div>
        <% end %>
      </div>
      <div class="other-items">
        <div class="title">他のお酒</div>
        <div class="all-items">
          <% 7.times do %>
          <div class="item">
            <div class="img"><%= image_tag("https://images-fe.ssl-images-amazon.com/images/I/3194SNNR5XL._SY445_QL70_.jpg") %></div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlcoholApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% twitter_card = get_twitter_card_info() %>
    <meta name="twitter:card" content=<%=twitter_card[:card]%> />
    <meta name="twitter:site" content=<%=twitter_card[:site]%> />
    <meta property="og:url" content=<%=twitter_card[:url]%> />
    <meta property="og:title" content=<%=twitter_card[:title]%> />
    <meta property="og:description" content=<%=twitter_card[:description]%> />
    <meta property="og:image" content=<%=twitter_card[:image]%> />
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <header>

  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="user-items-index">
  <div class="user-item-group">
    <div class="user-info">
      <div class="img"><%= image_tag "https://i.gyazo.com/c022ae94fdfe4688247e7b2fdd5f283a.jpg" %></div>
      <div class="name">@takoyaki0316のお気に入り</div>
    </div>
    <% 2.times do %>
    <div class="each-row">
      <% 2.times do %>
      <%= link_to item_path(1) do %>
      <div class="user-item">
        <div class="img">
          <%= image_tag("https://images-fe.ssl-images-amazon.com/images/I/3194SNNR5XL._SY445_QL70_.jpg") %>
        </div>
        <div class="user-item-name">
          カルサーダ・クイネア クイネア・レセルバ 750ml
        </div>
      </div>
      <% end %>
      <%= link_to item_path(1) do %>
      <div class="user-item">
        <div class="img">
          <%= image_tag("https://images-na.ssl-images-amazon.com/images/I/312xQCNFHcL.jpg") %>
        </div>
        <div class="user-item-name">
          カルサーダ・クイネア クイネア・レセルバ 750ml
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>